x

diff --git a/ga_sandbox/configure b/ga_sandbox/configure
--- a/ga_sandbox/configure
+++ b/ga_sandbox/configure
@@ -681,13 +681,13 @@ echo X"$0" |
   	  /^X\(\/\).*/{ s//\1/; q; }
   	  s/.*/./; q'`
   srcdir=$ac_confdir
-  if test ! -r $srcdir/$ac_unique_file; then
+  if test ! -r "$srcdir/$ac_unique_file"; then
     srcdir=..
   fi
 else
   ac_srcdir_defaulted=no
 fi
-if test ! -r $srcdir/$ac_unique_file; then
+if test ! -r "$srcdir/$ac_unique_file"; then
   if test "$ac_srcdir_defaulted" = yes; then
     { echo "$as_me: error: cannot find sources ($ac_unique_file) in $ac_confdir or .." >&2
    { (exit 1); exit 1; }; }
@@ -696,7 +696,7 @@ if test ! -r $srcdir/$ac_unique_file; then
    { (exit 1); exit 1; }; }
   fi
 fi
-(cd $srcdir && test -r ./$ac_unique_file) 2>/dev/null ||
+(cd $srcdir && test -r "./$ac_unique_file") 2>/dev/null ||
   { echo "$as_me: error: sources are in $srcdir, but \`cd $srcdir' does not work" >&2
    { (exit 1); exit 1; }; }
 srcdir=`echo "$srcdir" | sed 's%\([^\\/]\)[\\/]*$%\1%'`
@@ -5616,17 +5616,18 @@ echo $ECHO_N "checking for the fltk UI library... $ECHO_C" >&6
 if fltk-config --version >/dev/null 2>/dev/null; then
 	AQSIS_FLTK_VERSION=`fltk-config --version`
 	AQSIS_FLTK_CFLAGS=`fltk-config --cflags`
-	AQSIS_FLTK_LIBS=`fltk-config --ldflags`
 	AQSIS_FLTK_GL_CFLAGS=`fltk-config --cflags --use-gl`
+	AQSIS_FLTK_LIBS=`fltk-config --ldflags`
 	AQSIS_FLTK_GL_LIBS=`fltk-config --ldflags --use-gl`
 	echo "$as_me:$LINENO: result: found version $AQSIS_FLTK_VERSION" >&5
 echo "${ECHO_T}found version $AQSIS_FLTK_VERSION" >&6
 else
-	echo "$as_me:$LINENO: result: Warning: couldn't find fltk library" >&5
-echo "${ECHO_T}Warning: couldn't find fltk library" >&6
+	{ { echo "$as_me:$LINENO: error: couldn't find fltk library" >&5
+echo "$as_me: error: couldn't find fltk library" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
-                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ac_config_files="$ac_config_files Makefile vs.net/Makefile qhull-2003.1/Makefile qhull-2003.1/src/Makefile qhull-2003.1/html/Makefile qhull-2003.1/eg/Makefile qhull-2003.1/vs.net/Makefile libgasandbox/Makefile chap1/Makefile chap1/ex1/Makefile chap2/Makefile chap2/ex1/Makefile chap2/ex2/Makefile chap2/ex3/Makefile chap3/Makefile chap3/ex1/Makefile chap3/ex2/Makefile chap3/ex3/Makefile chap3/ex4/Makefile chap4/Makefile chap4/ex1/Makefile chap4/ex2/Makefile chap4/ex3/Makefile chap5/Makefile chap5/ex1/Makefile chap5/ex2/Makefile chap5/ex3/Makefile chap6/Makefile chap6/ex1/Makefile chap6/ex2/Makefile chap7/Makefile chap7/ex1/Makefile chap7/ex2/Makefile chap7/ex3/Makefile chap7/ex4/Makefile chap7/ex5/Makefile chap8/Makefile chap10/Makefile chap10/ex1/Makefile chap10/ex2/Makefile chap10/ex3/Makefile chap11/Makefile chap11/ex1/Makefile chap11/ex2/Makefile chap11/ex3/Makefile chap11/ex4/Makefile chap12/Makefile chap12/ex1/Makefile chap12/ex2/Makefile chap12/ex3/Makefile chap13/Makefile chap13/ex1/Makefile chap13/ex2/Makefile chap13/ex3/Makefile chap13/ex4/Makefile chap14/Makefile chap14/ex1/Makefile chap14/ex2/Makefile chap14/ex3/Makefile chap14/ex4/Makefile chap15/Makefile chap15/ex1/Makefile chap15/ex2/Makefile chap15/ex3/Makefile chap16/Makefile chap16/ex1/Makefile chap16/ex2/Makefile chap16/ex3/Makefile chap16/ex4/Makefile solutions/Makefile solutions/chap2/Makefile solutions/chap2/ex2/Makefile solutions/chap3/Makefile solutions/chap3/ex2/Makefile solutions/chap6/Makefile solutions/chap6/ex1/Makefile solutions/chap7/Makefile solutions/chap7/ex4/Makefile solutions/chap7/ex5/Makefile solutions/chap11/Makefile solutions/chap11/ex4/Makefile solutions/chap13/Makefile solutions/chap13/ex2/Makefile solutions/chap14/Makefile solutions/chap14/ex2/Makefile solutions/vs.net/Makefile attic/Makefile attic/gaigen2hp/Makefile screenshots/Makefile"
+                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ac_config_files="$ac_config_files Makefile vs.net/Makefile qhull-2003.1/Makefile qhull-2003.1/src/Makefile qhull-2003.1/html/Makefile qhull-2003.1/eg/Makefile qhull-2003.1/vs.net/Makefile libgasandbox/Makefile libgasandbox_no_opt/Makefile chap1/Makefile chap1/ex1/Makefile chap2/Makefile chap2/ex1/Makefile chap2/ex2/Makefile chap2/ex3/Makefile chap3/Makefile chap3/ex1/Makefile chap3/ex2/Makefile chap3/ex3/Makefile chap3/ex4/Makefile chap4/Makefile chap4/ex1/Makefile chap4/ex2/Makefile chap4/ex3/Makefile chap5/Makefile chap5/ex1/Makefile chap5/ex2/Makefile chap5/ex3/Makefile chap6/Makefile chap6/ex1/Makefile chap6/ex2/Makefile chap7/Makefile chap7/ex1/Makefile chap7/ex2/Makefile chap7/ex3/Makefile chap7/ex4/Makefile chap7/ex5/Makefile chap8/Makefile chap10/Makefile chap10/ex1/Makefile chap10/ex2/Makefile chap10/ex3/Makefile chap11/Makefile chap11/ex1/Makefile chap11/ex2/Makefile chap11/ex3/Makefile chap11/ex4/Makefile chap12/Makefile chap12/ex1/Makefile chap12/ex2/Makefile chap12/ex3/Makefile chap13/Makefile chap13/ex1/Makefile chap13/ex2/Makefile chap13/ex3/Makefile chap13/ex4/Makefile chap14/Makefile chap14/ex1/Makefile chap14/ex2/Makefile chap14/ex3/Makefile chap14/ex4/Makefile chap15/Makefile chap15/ex1/Makefile chap15/ex2/Makefile chap15/ex3/Makefile chap16/Makefile chap16/ex1/Makefile chap16/ex2/Makefile chap16/ex3/Makefile chap16/ex4/Makefile solutions/Makefile solutions/chap2/Makefile solutions/chap2/ex2/Makefile solutions/chap3/Makefile solutions/chap3/ex2/Makefile solutions/chap6/Makefile solutions/chap6/ex1/Makefile solutions/chap7/Makefile solutions/chap7/ex4/Makefile solutions/chap7/ex5/Makefile solutions/chap11/Makefile solutions/chap11/ex4/Makefile solutions/chap13/Makefile solutions/chap13/ex2/Makefile solutions/chap14/Makefile solutions/chap14/ex2/Makefile solutions/vs.net/Makefile attic/Makefile attic/gaigen2hp/Makefile screenshots/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -6217,6 +6218,7 @@ do
   "qhull-2003.1/eg/Makefile" ) CONFIG_FILES="$CONFIG_FILES qhull-2003.1/eg/Makefile" ;;
   "qhull-2003.1/vs.net/Makefile" ) CONFIG_FILES="$CONFIG_FILES qhull-2003.1/vs.net/Makefile" ;;
   "libgasandbox/Makefile" ) CONFIG_FILES="$CONFIG_FILES libgasandbox/Makefile" ;;
+  "libgasandbox_no_opt/Makefile" ) CONFIG_FILES="$CONFIG_FILES libgasandbox_no_opt/Makefile" ;;
   "chap1/Makefile" ) CONFIG_FILES="$CONFIG_FILES chap1/Makefile" ;;
   "chap1/ex1/Makefile" ) CONFIG_FILES="$CONFIG_FILES chap1/ex1/Makefile" ;;
   "chap2/Makefile" ) CONFIG_FILES="$CONFIG_FILES chap2/Makefile" ;;
